### ISSUE TITLE
No module named 'gradio'

### ISSUE THREAD

**Issue by GrahamboJangles** [pythoninoffice/amd_webui#5]
First off I want to say you're a genius for creating a script that automates the installation process including virtual environment, I don't know why people don't do that more often.

However, I get this error when running the script:

```
venv "C:\stable diffusion\amd_webui-main\venv\Scripts\Python.exe"
You are using python version - 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
installing requirements
Processing c:\stable diffusion\amd_webui-main\repositories\ort_nightly_directml-1.13.0.dev20220908001-cp310-cp310-win_amd64.whl
Requirement already satisfied: numpy>=1.21.6 in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (1.24.1)
Requirement already satisfied: packaging in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (23.0)
Requirement already satisfied: sympy in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (1.11.1)
Requirement already satisfied: coloredlogs in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (15.0.1)
Requirement already satisfied: protobuf in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (4.21.12)
Requirement already satisfied: flatbuffers in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (23.1.4)
Requirement already satisfied: humanfriendly>=9.1 in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from coloredlogs->ort-nightly-directml==1.13.0.dev20220908001) (10.0)
Requirement already satisfied: mpmath>=0.19 in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from sympy->ort-nightly-directml==1.13.0.dev20220908001) (1.2.1)
Requirement already satisfied: pyreadline3 in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->ort-nightly-directml==1.13.0.dev20220908001) (3.4.1)
ort-nightly-directml is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
You should consider upgrading via the 'D:\stable diffusion\amd_webui-main\venv\Scripts\python.exe -m pip install --upgrade pip' command.
Done installing
Traceback (most recent call last):
  File "C:\stable diffusion\amd_webui-main\start_app.py", line 69, in <module>
    import amd_webui
  File "C:\stable diffusion\amd_webui-main\amd_webui.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

**Comment by GrahamboJangles** [comment]
I fixed this error by adding `pip_install('gradio')` on line 67 in start_app.py, but now I get this error:

```
start_app.py
You are using python version - 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
installing requirements
Processing c:\stable diffusion\amd_webui-main\repositories\ort_nightly_directml-1.13.0.dev20220908001-cp310-cp310-win_amd64.whl
Requirement already satisfied: flatbuffers in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (23.1.4)
Requirement already satisfied: protobuf in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (4.21.12)
Requirement already satisfied: numpy>=1.21.6 in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (1.24.1)
Requirement already satisfied: packaging in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (23.0)
Requirement already satisfied: sympy in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (1.11.1)
Requirement already satisfied: coloredlogs in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from ort-nightly-directml==1.13.0.dev20220908001) (15.0.1)
Requirement already satisfied: humanfriendly>=9.1 in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from coloredlogs->ort-nightly-directml==1.13.0.dev20220908001) (10.0)
Requirement already satisfied: mpmath>=0.19 in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from sympy->ort-nightly-directml==1.13.0.dev20220908001) (1.2.1)
Requirement already satisfied: pyreadline3 in c:\stable diffusion\amd_webui-main\venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->ort-nightly-directml==1.13.0.dev20220908001) (3.4.1)
ort-nightly-directml is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
You should consider upgrading via the 'C:\stable diffusion\amd_webui-main\venv\Scripts\python.exe -m pip install --upgrade pip' command.
Done installing
Traceback (most recent call last):
  File "D:\stable diffusion\amd_webui-main\start_app.py", line 69, in <module>
    import amd_webui
  File "C:\stable diffusion\amd_webui-main\amd_webui.py", line 2, in <module>
    from diffusers import OnnxStableDiffusionPipeline, OnnxStableDiffusionImg2ImgPipeline
ModuleNotFoundError: No module named 'diffusers'
```

I have tried reopening the start.bat script multiple times and it doesn't open any webpage.

**Comment by GrahamboJangles** [comment]
I fixed that error by adding `pip_install("diffusers")` to line 68 in start_app.py.

**Comment by GrahamboJangles** [comment]
Now I'm stuck.

```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable diffusion\amd_webui-main\amd_webui.py", line 47, in txt2img
    image = pipe(prompt,
NameError: name 'pipe' is not defined
```

**Comment by GNEFNEHCUIQ** [comment]
> Now I'm stuck.
> 
> ```
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> Traceback (most recent call last):
>   File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
>     output = await app.get_blocks().process_api(
>   File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
>     result = await self.call_function(
>   File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "C:\stable diffusion\amd_webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "C:\stable diffusion\amd_webui-main\amd_webui.py", line 47, in txt2img
>     image = pipe(prompt,
> NameError: name 'pipe' is not defined
> ```

i fix it by change `pip_install("diffusers") ` to `pip_install("-e git+https://github.com/huggingface/diffusers#egg=diffusers")` in start_app.py.
